from pathlib import Path

p = Path('dev/v403-edevlet-candidate/build_v403_edevlet.py')
s = p.read_text(encoding='utf-8')

def one(old, new, label):
    global s
    n = s.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, found {n}')
    s = s.replace(old, new, 1)

one("from pathlib import Path\n", "from pathlib import Path\nfrom desktop_app_patch import patch_desktop_source\nfrom unified_source_patch import patch_server_source, patch_admin_source\nfrom manager_patch import patch_manager_source, patch_manager_ensure_source\n", 'unified patch imports')
one("NESTED = 'pro-components/yazici-pro.zip'\nSUPERVISOR = 'KafePin_Update_Supervisor.js'\nALLOWED_OUTER = {'update.json', NESTED, SUPERVISOR}", "NESTED = 'pro-components/yazici-pro.zip'\nSUPERVISOR = 'KafePin_Update_Supervisor.js'\nDESKTOP = 'desktop-app/KafePinProDesktop.cs'\nSERVER = 'server.js'\nADMIN = 'public/admin.html'\nMANAGER = 'KafePin_System_Manager.ps1'\nMANAGER_ENSURE = 'KafePin_Manager_Ensure.ps1'\nALLOWED_OUTER = {'update.json', NESTED, SUPERVISOR, DESKTOP, SERVER, ADMIN, MANAGER, MANAGER_ENSURE}", 'unified outer allowlist')
one("        supervisor_bytes = outer.read(SUPERVISOR)\n        patched_supervisor = patch_supervisor(supervisor_bytes.decode('utf-8-sig')).encode('utf-8')", "        supervisor_bytes = outer.read(SUPERVISOR)\n        patched_supervisor = patch_supervisor(supervisor_bytes.decode('utf-8-sig')).encode('utf-8')\n        patched_desktop = patch_desktop_source(outer.read(DESKTOP))\n        patched_server = patch_server_source(outer.read(SERVER))\n        patched_admin = patch_admin_source(outer.read(ADMIN))\n        patched_manager = patch_manager_source(outer.read(MANAGER))\n        patched_manager_ensure = patch_manager_ensure_source(outer.read(MANAGER_ENSURE))", 'unified source payload')
one("            update['files'] = [SUPERVISOR, NESTED]", "            update['files'] = [SUPERVISOR, NESTED, DESKTOP, SERVER, ADMIN, MANAGER, MANAGER_ENSURE]", 'unified update files')
one("                    elif info.filename == SUPERVISOR:\n                        data = patched_supervisor\n                    outz.writestr(info, data)", "                    elif info.filename == SUPERVISOR:\n                        data = patched_supervisor\n                    elif info.filename == DESKTOP:\n                        data = patched_desktop\n                    elif info.filename == SERVER:\n                        data = patched_server\n                    elif info.filename == ADMIN:\n                        data = patched_admin\n                    elif info.filename == MANAGER:\n                        data = patched_manager\n                    elif info.filename == MANAGER_ENSURE:\n                        data = patched_manager_ensure\n                    outz.writestr(info, data)", 'unified outer write')
one("OUT_NAME = 'KafePin-Pro-Update-v4.0.3-CANDIDATE3.zip'", "OUT_NAME = 'KafePin-Pro-Update-v4.0.3-UNIFIED-TEST-CANDIDATE.zip'", 'unified output name')
one("(root / 'KafePin-Pro-Update-v4.0.3-CANDIDATE3.sha256.txt')", "(root / 'KafePin-Pro-Update-v4.0.3-UNIFIED-TEST-CANDIDATE.sha256.txt')", 'unified checksum name')
one("(root / 'V4.0.3-EDEVLET-CANDIDATE-TEST-REPORT.md')", "(root / 'V4.0.3-UNIFIED-TEST-CANDIDATE-REPORT.md')", 'unified report name')
one("'v403-candidate3-edevlet-fast-r3'", "'v403-unified-test-candidate-r1'", 'unified revision')
one("    const componentOnly=updateFiles.length===2 && updateFiles.includes('KafePin_Update_Supervisor.js') && updateFiles.includes('pro-components/yazici-pro.zip');", "    const unifiedTarget=updateFiles.length===7 && updateFiles.includes('KafePin_Update_Supervisor.js') && updateFiles.includes('pro-components/yazici-pro.zip') && updateFiles.includes('desktop-app/KafePinProDesktop.cs') && updateFiles.includes('server.js') && updateFiles.includes('public/admin.html') && updateFiles.includes('KafePin_System_Manager.ps1') && updateFiles.includes('KafePin_Manager_Ensure.ps1');\n    const componentOnly=unifiedTarget || (updateFiles.length===2 && updateFiles.includes('KafePin_Update_Supervisor.js') && updateFiles.includes('pro-components/yazici-pro.zip'));", 'unified supervisor target')
one("    if(componentOnly){\n      const manager=path.join(installRoot,'KafePin_Pro_Component_Manager.ps1');", "    if(componentOnly){\n      if(unifiedTarget){\n        shell=await ensureDesktopShellExact(installRoot);\n        const managerEnsure=path.join(installRoot,'KafePin_Manager_Ensure.ps1');\n        const ensured=run('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',managerEnsure,'-InstallRoot',installRoot,'-NodePath',process.execPath],{timeout:35000});\n        if(ensured.code!==0) throw new Error(`Server Manager activation failed: ${(ensured.stderr||ensured.stdout).trim().slice(0,900)}`);\n        log(installRoot,'unified activation: Server Manager payload synchronized');\n      }\n      const manager=path.join(installRoot,'KafePin_Pro_Component_Manager.ps1');", 'necessary desktop shell and manager refresh')
one("'v4.0.3 TEST/CANDIDATE2: hedefli hızlı güncelleme; ana masaüstü kabuğu ve diğer PRO modülleri refresh edilmez, yalnız Yazıcı PRO güncellenir.'", "'v4.0.3 UNIFIED TEST: doğrulanmış fail-safe, Yazıcı PRO/e-Devlet ve EveryCafe recovery düzeltmeleri tek adayda birleştirildi.'", 'unified note')
one("- Outer değişen girdiler: `update.json`, `KafePin_Update_Supervisor.js`, `pro-components/yazici-pro.zip`", "- Outer değişen girdiler: `update.json`, `KafePin_Update_Supervisor.js`, `pro-components/yazici-pro.zip`, `desktop-app/KafePinProDesktop.cs`, `server.js`, `public/admin.html`, `KafePin_System_Manager.ps1`, `KafePin_Manager_Ensure.ps1`", 'unified report files')
one("- `server.js`, updater, rollback, DB güvenliği, EveryCafe, finans, session/spin ve diğer PRO paketleri byte-for-byte v4.0.2 ile aynıdır.", "- Server değişiklikleri hedefli fail-safe lock recovery, child timer race, bounded SQLITE_BUSY retry ve read-only EveryCafe recovery endpointidir; finance/session/spin semantiği korunur.", 'unified protection report')
p.write_text(s, encoding='utf-8')
print('UNIFIED_CANDIDATE_PATCH_OK')
