const grid=document.getElementById('grid'),status=document.getElementById('status'),actions=document.getElementById('actions');
const fmt=(n,s='')=>Number.isFinite(Number(n))?`${Number(n).toFixed(Number(n)>=100?0:1)}${s}`:'—';
function metric(label,value,cls=''){return `<div class="metric ${cls}"><small>${label}</small><strong>${value}</strong></div>`}
function limitBadge(c){const w=c.webLimit||{};if(!c.online)return '<span class="limit-badge off">WEB LİMİTİ: OFFLINE</span>';if(!w.reachable)return '<span class="limit-badge err">WEB LİMİTİ: AGENT YOK</span>';if(w.enabled)return `<span class="limit-badge on">WEB LİMİTİ: AKTİF ${Math.round(w.downMbps||50)}/${Math.round(w.upMbps||10)}</span>`;return '<span class="limit-badge off">WEB LİMİTİ: KAPALI</span>'}
function limitButtons(c){const w=c.webLimit||{};const disabled=!c.online||!c.ip||!w.reachable;return `<div class="limit-actions"><button ${disabled?'disabled':''} onclick="setLimit('${encodeURIComponent(c.ip||'')}',true,this)">50/10 Aç</button><button ${disabled?'disabled':''} class="danger" onclick="setLimit('${encodeURIComponent(c.ip||'')}',false,this)">Kapat</button></div>`}
function render(clients){if(!clients.length){grid.innerHTML='<div class="empty">Client bulunamadı.</div>';return}grid.innerHTML=clients.map(c=>{const state=c.sensorOnline?'Libre bağlı':c.online?'Sensör kapalı':'Offline';const link=Number(c.linkSpeedMbps)||0;const linkSlow=link>0&&link<1000;const linkText=link>0?`${Math.round(link)} Mbps`:'—';return `<article class="card ${c.online?'':'offline'}"><div class="top"><div><div class="name">${c.name}</div><div class="ip">${c.ip||'IP yok'}</div></div><span class="badge ${c.sensorOnline?'':'warn'}">${state}</span></div><div class="limit-row">${limitBadge(c)}${limitButtons(c)}</div><div class="metric-grid">${metric('CPU',fmt(c.cpuLoad,'%'))}${metric('RAM',fmt(c.ramLoad,'%'))}${metric('CPU sıcaklığı',fmt(c.cpuTemp,' °C'),Number(c.cpuTemp)>=80?'hot':'')}${metric('GPU sıcaklığı',fmt(c.gpuTemp,' °C'),Number(c.gpuTemp)>=85?'hot':'')}${metric('İndirme',fmt(c.downloadMbps,' Mbps'),'net')}${metric('Yükleme',fmt(c.uploadMbps,' Mbps'),'net')}${metric('Ping',fmt(c.pingMs,' ms'),'net')}${metric('Bağlantı hızı',linkText,`net link-speed ${linkSlow?'link-slow':''}`)}</div><p class="message">${c.message||''}${(c.webLimit||{}).error?` • Web limit: ${(c.webLimit||{}).error}`:''}</p></article>`}).join('')}
async function post(url,payload){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
async function setLimit(ipEncoded,enable,btn){const ip=decodeURIComponent(ipEncoded);if(btn)btn.disabled=true;try{await post('/api/web-limit',{ip,enable});status.textContent=`${ip} • WEB LİMİTİ ${enable?'50/10 AÇILDI':'KAPATILDI'}`;await load()}catch(e){status.textContent=`Web limit hatası: ${e.message}`}finally{if(btn)btn.disabled=false}}
async function setAll(enable){const buttons=[...actions.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const d=await post('/api/web-limit/all',{enable});const ok=(d.results||[]).filter(x=>x.ok).length,fail=(d.results||[]).filter(x=>!x.ok&&!x.skipped).length,skip=(d.results||[]).filter(x=>x.skipped).length;status.textContent=`Tüm masalar: ${ok} başarılı${fail?` • ${fail} hata`:''}${skip?` • ${skip} offline`:''}`;await load()}catch(e){status.textContent=`Toplu web limit hatası: ${e.message}`}finally{buttons.forEach(b=>b.disabled=false)}}
async function load(){try{const r=await fetch('/api/metrics?_='+Date.now(),{cache:'no-store'}),d=await r.json();if(!d.ok)throw Error(d.error);render(d.clients||[]);const sensors=(d.clients||[]).filter(x=>x.sensorOnline).length,limits=(d.clients||[]).filter(x=>(x.webLimit||{}).reachable&&(x.webLimit||{}).enabled).length;status.textContent=`${sensors} sensör bağlı • ${limits} web limiti aktif • ${new Date(d.updatedAt).toLocaleTimeString('tr-TR')}`}catch(e){status.textContent='Bağlantı hatası';grid.innerHTML=`<div class="empty">${e.message}</div>`}}
load();setInterval(load,3000);
